name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build Docker image
        run: docker build -t redis_main .

      - name: Save Docker image to file
        run: docker save redis_main | gzip > redis_main.tar.gz

      - name: Upload Docker image to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: redis_main
          path: redis_main.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image from build job
        uses: actions/download-artifact@v2
        with:
          name: redis_main
          path: redis_main.tar.gz

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: redis_main.tar.gz
          target: ~/redis_main.tar.gz

      - name: SSH into VPS and load Docker image
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker load -i ~/redis_main.tar.gz
            docker stop my_rust_container || true
            docker rm my_rust_container || true
            docker run --name my_rust_container -d redis_main
